# To run:
# ansible-playbook playbooks/eos-prod/graylog-setup.yaml -i inventories/eos.yaml --become-password-file=credentials/ansible_eos_password.txt
# To Test:
# ansible-playbook playbooks/eos-prod/graylog-setup.yaml --check -i inventories/eos.yaml --become-password-file=credentials/ansible_eos_password.txt
---
- name: Install and configure the Sovereign nodes for Graylog
  hosts: gpu
  remote_user: ansible
  become: true

  tasks:
    - name: Import needed tasks
      ansible.builtin.include_tasks:
        file: ../../tasks/max_map_count.yaml