# To run:
# ansible-playbook playbooks/eos-prod/graylog-setup.yaml -i inventories/eos.yaml --become-password-file=credentials/ansible_eos_password.txt
# To Test:
# ansible-playbook playbooks/eos-prod/graylog-setup.yaml --check -i inventories/eos.yaml --become-password-file=credentials/ansible_eos_password.txt
---
- name: Install and configure the Graylog nodes
  hosts: graylog
  remote_user: ansible
  become: true

  tasks:
    - name: Import and run the needed tasks
      ansible.builtin.include_tasks:
        file: "{{ task_list }}"
      loop:
        - ../../tasks/qemu_guest_agent.yaml
        - ../../tasks/max_map_count.yaml
      loop_control:
        loop_var: task_list