version: '3.8'

services:
  overseerr:
    image: ghcr.io/hotio/overseerr
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Chicago
    volumes:
      - '/mnt/ceph/overseerr_data:/config'
    ports:
      - 5055:5055
    networks:
      - media
      - local_proxy
      - cftunnel
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - shepherd.updates=true
        - homepage.group=Media Front End
        - homepage.name=Overseerr
        - homepage.icon=overseerr.png
        - homepage.href=http://overseerr.eos.local.sch-apps.com
        - homepage.description=Overseerr media requests
        - traefik.enable=true
        - traefik.http.routers.overseerr-rtr.entrypoints=web
        - traefik.http.routers.overseerr-rtr.rule=Host(`overseerr.eos.local.sch-apps.com`)
        - traefik.http.routers.overseerr-rtr.service=overseerr-svc
        - traefik.http.services.overseerr-svc.loadbalancer.server.port=5055

volumes:
  overseerr_data:
    driver: local

networks:
  media:
    external: true
  local_proxy:
    external: true
  cftunnel:
    external: true