version: '3.8'

services:
  overseerr:
    image: ghcr.io/hotio/overseerr
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Chicago
    volumes:
      - '/mnt/ceph/overseerr_data:/config'
    ports:
      - 5055:5055
    restart: unless-stopped
    networks:
      - media
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "shepherd.updates=true"

volumes:
  overseerr_data:
    driver: local

networks:
  media:
    external: true
  proxy:
    external: true