# To run:
# ansible-playbook playbooks/jovian-prod/apps-prod.yml -i inventories/eos-v2.yml --become-password-file=credentials/ansible_eos_password.txt
# To Test:
# ansible-playbook playbooks/jovian-prod/apps-prod.yml --check -i inventories/eos-v2.yml --become-password-file=credentials/ansible_eos_password.txt
---
- name: Run the configured Jovian Prod apps task files
  hosts: jupiter-01
  remote_user: ansible
  become: true
  vars_files:
    - ../../vars/jovian-prod/secrets.yml

  tasks:
    - name: Import and execute app deployment tasks
      ansible.builtin.include_tasks:
        file: "{{ task_list }}"
      loop:
        - ../../tasks/jovian-prod/env-secrets.yml
        # - ../../tasks/jovian-prod/promtail.yml
        # - ../../tasks/jovian-prod/mkvtoolnix.yml

        # - ../../tasks/jovian-prod/nvidia-smi-tester.yml

        # - ../../tasks/jovian-prod/restic-restore.yml

      loop_control:
        loop_var: task_list
