version: '3.8'

services:
  grafana:
    image: grafana/grafana-oss
    ports:
      - '3000:3000'
    environment:
      - TZ=America/Chicago
    volumes:
      - '/mnt/ceph/grafana_data:/var/lib/grafana'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "shepherd.updates=true"
    networks:
      - monitoring

  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - '/mnt/ceph/uptime-kuma_data:/app/data'
    ports:
      # <Host Port>:<Container Port>
      - 3001:3001
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - traefik.enable=true
        - traefik.http.routers.uptime-kuma-rtr.entrypoints=web
        - traefik.http.routers.uptime-kuma-rtr.rule=Host(`uptime-kuma.local.sch-apps.com`)
        - traefik.http.routers.uptime-kuma-rtr.service=uptime-kuma-svc
        - traefik.http.services.uptime-kuma-svc.loadbalancer.server.port=3001
        - shepherd.updates=true"
        - homepage.group=Eos Swarm Cluster
        - homepage.name=Uptime-Kuma
        - homepage.icon=Uptime-Kuma.png
        - homepage.href=http://uptime-kuma.local.sch-apps.com
        - homepage.description=External service status
        - homepage.widget.type=uptimekuma
        - homepage.widget.target=_blank
        - homepage.widget.url=http://192.168.6.7:3001
        - homepage.widget.slug=all-homelab-services
    networks:
      - monitoring
      - dockerproxy
      - media
      - local_proxy

  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - '/mnt/ceph/chronograf_data:/usr/lib/chronograf'
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=$INFLUXDB_ADMIN_USER
      - INFLUXDB_PASSWORD=$INFLUXDB_ADMIN_PASSWORD
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.chronograf-rtr.entrypoints=web"
        - "traefik.http.routers.chronograf-rtr.rule=Host(`chronograf.local.sch-apps.com`)"
        - "traefik.http.routers.chronograf-rtr.service=chronograf-svc"
        - "traefik.http.services.chronograf-svc.loadbalancer.server.port=8888"
        - "shepherd.updates=true"
    networks:
      - monitoring

volumes:
  grafana_data:
    driver: local
  chronograf_data:
    driver: local
  uptime-kuma_data:
    driver: local

networks:
  monitoring:
    name: monitoring
    driver: overlay
    attachable: true
  dockerproxy:
    external: true
  media:
    external: true
  local_proxy:
    external: true