version: '3.8'

services:
  grafana:
    image: grafana/grafana-oss
    ports:
      - '3000:3000'
    environment:
      - TZ=America/Chicago
    volumes:
      - '/mnt/ceph/grafana_data:/var/lib/grafana'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "shepherd.updates=true"
    networks:
      - monitoring
      - proxy

  influxdb:
    image: influxdb:1.8.10
    secrets:
      - source: influxdb_user
        target: influx_user
      - source: influxdb_password
        target: influx_password
    environment:
      - TZ=America/Chicago
      - INFLUXDB_USERNAME=/run/secrets/influx_user
      - INFLUXDB_PASSWORD=/run/secrets/influx_password
    ports:
      - '8086:8086'
    volumes:
      - '/mnt/ceph/influxdb_data:/var/lib/influxdb'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "shepherd.updates=true"
    networks:
      - monitoring
      - proxy

  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - '/mnt/ceph/chronograf_data:/var/lib/chronograf'
    secrets:
      - source: influxdb_user
        target: influx_user
      - source: influxdb_password
        target: influx_password
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=/run/secrets/influx_user
      - INFLUXDB_PASSWORD=/run/secrets/influx_password
      - TZ=America/Chicago
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "shepherd.updates=true"
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.7.5
    ports:
      - '3100:3100'
    environment:
      - TZ=America/Chicago
    volumes:
      - '/mnt/ceph/loki_data:/etc/loki'
    command: -config.file=/etc/loki/local-config.yaml
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "shepherd.updates=true"
    networks:
      - monitoring
      - proxy

  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - '/mnt/ceph/uptime-kuma_data:/app/data'
    ports:
      # <Host Port>:<Container Port>
      - 3001:3001
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "shepherd.updates=true"
    networks:
      - monitoring
      - proxy
      - dockerproxy
      - media

  prometheus:
    image: prom/prometheus
    volumes:
      - '/mnt/ceph/prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml'
    networks:
      - monitoring
    ports:
      - 9090:9090

volumes:
  grafana_data:
    driver: local
  influxdb_data:
    driver: local
  chronograf_data:
    driver: local
  loki_data:
    driver: local
  uptime-kuma_data:
    driver: local
  prometheus_data:
    driver: local

secrets:
  influxdb_user:
    external: true
  influxdb_password:
    external: true

networks:
  monitoring:
    name: monitoring
    driver: overlay
    attachable: true
  proxy:
    external: true
  dockerproxy:
    external: true
  media:
    external: true