version: '3.8'

services:
  uptime-kuma:
    image: 'louislam/uptime-kuma:1'
    container_name: uptime-kuma
    restart: always
    ports:
      - '3001:3001'
    volumes:
      - /var/lib/docker/volumes/uptime-kuma_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cftunnel
      - gluetun

networks:
  cftunnel:
    external: true
  gluetun:
    external: true