apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: plex
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: plexinc/pms-docker:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 32400
          name: plex
        - containerPort: 8324
          name: plex-roku
        - containerPort: 32469
          name: plex-dlna
        - containerPort: 1900
          name: plex-upnp
          protocol: UDP
        - containerPort: 32410
          name: plex-gdm-1
          protocol: UDP
        - containerPort: 32412
          name: plex-gdm-2
          protocol: UDP
        - containerPort: 32413
          name: plex-gdm-3
          protocol: UDP
        - containerPort: 32414
          name: plex-gdm-4
          protocol: UDP       
        volumeMounts:
        - name: config
          mountPath: /config
        - mountPath: /Films
          name: plex-nfs
          readOnly: true
          subPath: video-movies
        - mountPath: /TVShows
          name: plex-nfs
          readOnly: true
          subPath: video-tv
        - name: plex-transcode
          mountPath: /transcode
        - name: dev-dri
          mountPath: /dev/dri
          readOnly: true
        env:
        - name: ADVERTISE_IP
          value: 'http://192.168.2.5:32400/,https://my-plex-domain'
        - name: ALLOWED_NETWORKS
          value: 192.168.0.0/16,10.0.0.0/8
        - name: PLEX_CLAIM
          value: claim-your-claim
        - name: PLEX_UID
          value: "1000"
        - name: PLEX_GID
          value: "1000"
        - name: HOSTNAME
          value: plex
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: plex-pvc
          readOnly: false
      - name: plex-nfs
        hostPath:
          path: /nfs
      - name: plex-transcode
        persistentVolumeClaim:
          claimName: plex-transcode
      - name: dev-dri
        hostPath:
          path: /dev/dri
---
apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  type: LoadBalancer
  ports:
  - port: 32400
    targetPort: plex
    name: plex
  - port: 8324
    targetPort: plex-roku
    name: plex-roku
  - port: 32469
    targetPort: plex-dlna
    name: plex-dlna
  - port: 1900
    targetPort: plex-upnp
    name: plex-upnp
    protocol: UDP
  - port: 32410
    targetPort: plex-gdm-1
    name: plex-gdm-1
    protocol: UDP
  - port: 32412
    targetPort: plex-gdm-2
    name: plex-gdm-2
    protocol: UDP
  - port: 32413
    targetPort: plex-gdm-3
    name: plex-gdm-3
    protocol: UDP
  - port: 32414
    targetPort: plex-gdm-4
    name: plex-gdm-4
    protocol: UDP
  selector:
    app: plex
  loadBalancerIP: 192.168.2.5 
