apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: jovian-prod
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
      - name: prowlarr
        image: ghcr.io/hotio/prowlarr
        imagePullPolicy: Always
        ports:
        - containerPort: 9696
          name: http     
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: prowlarr-pvc
          readOnly: false

---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr-service
  namespace: jovian-prod
spec:
  selector:
    app: prowlarr
  ports:
    - port: 9696
      targetPort: http
      protocol: TCP
      name: http
  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  namespace: jovian-prod
spec:
  rules:
    - host: prowlarr.jovian.local.sch-apps.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  prowlarr-service
                port:
                  number: 9696

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-pvc
  namespace: jovian-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: k8s-cephfs
  resources:
    requests:
      storage: 1Gi