apiVersion: v1
kind: Pod
metadata:
  name: tautulli
  namespace: jovian-prod
  labels:
    app:
      tautulli
spec:
  containers:
    - name: tautulli
      image: ghcr.io/tautulli/tautulli:latest
      imagePullPolicy: Always
      volumeMounts:
        - name: config
          mountPath: /config
      ports:
        - name: http
          containerPort: 8181
          protocol: TCP
  volumes:
    - name: config
      persistentVolumeClaim:
        claimName: tautulli-pvc
        readOnly: false

---
apiVersion: v1
kind: Service
metadata:
  name: tautulli-service
  namespace: jovian-prod
spec:
  selector:
    app: tautulli
  ports:
    - port: 8181
      targetPort: http
      protocol: TCP
      name: http
  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tautulli
  namespace: jovian-prod
spec:
  rules:
    - host: tautulli.jovian.local.sch-apps.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  tautulli-service
                port:
                  number: 8181

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-pvc
  namespace: jovian-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: k8s-cephfs
  resources:
    requests:
      storage: 10Gi

