version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - TZ=America/Chicago
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 3 * * * #run every day at 3am
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock