version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Chicago
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - '/dev/shm:/config/transcodes'
      - jellyfin_data:/config
      - '/mnt/hdd_pool:/hdd_pool_media:/hdd_pool'
      - '/mnt/samba/media/media:/samba_media:ro'
    networks:
      - outside
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.nvidia == true"
      labels:
        - shepherd.updates=true
        - homepage.group=Media Front End
        - homepage.name=Jellyfin
        - homepage.icon=jellyfin.png
        - homepage.href=https://jellyfin.sch-apps.com
        - homepage.description=Jellyfin media server
        - docker-volume-backup.stop-during-backup=jellyfin_backup

  jellystat-db:
    image: postgres:15.2
    environment:
      - POSTGRES_DB=jellystat
      - POSTGRES_USER=$jellystatdb_user
      - POSTGRES_PASSWORD=$jellystatdb_password
    volumes:
    - jellystat-db:/var/lib/postgresql/data
    networks:
      - jellystat
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - shepherd.updates=true
        - docker-volume-backup.stop-during-backup=jellyfin_backup

  jellystat:
    image: cyfershepard/jellystat:latest
    environment:
      - POSTGRES_USER=$jellystatdb_user
      - POSTGRES_PASSWORD=$jellystatdb_password
      - POSTGRES_IP=jellystat-db
      - POSTGRES_PORT=5432
      - JWT_SECRET=$jellystat_password
    ports:
      - "3002:3000"
    volumes:
      - jellystat-data:/app/backend/backup-data
    networks:
      - media
      - jellystat
      - local_proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - traefik.enable=true
        - traefik.http.routers.jellystat-rtr.entrypoints=web
        - traefik.http.routers.jellystat-rtr.rule=Host(`jellystat.local.sch-apps.com`)
        - traefik.http.routers.jellystat-rtr.service=jellystat-svc
        - traefik.http.services.jellystat-svc.loadbalancer.server.port=3000
        - shepherd.updates=true
        - docker-volume-backup.stop-during-backup=jellyfin_backup
        - homepage.group=Media Tools
        - homepage.name=Jellystat
        - homepage.icon=jellystat.png
        - homepage.description=Jellyfin server stats and metrics
        - homepage.href=http://jellystat.local.sch-apps.com

  backup:
    image: offen/docker-volume-backup:v2
    environment:
      - BACKUP_FILENAME=jellyfin-%Y-%m-%dT%H-%M-%S.tar.gz
      - BACKUP_CRON_EXPRESSION=0 7 * * * #Run at 7am UTC, 2AM CST
      - BACKUP_PRUNING_PREFIX=jellyfin-
      - BACKUP_RETENTION_DAYS=5
      - GZIP_PARALLELISM=3
      - BACKUP_STOP_DURING_BACKUP_LABEL=jellyfin_backup
    volumes:
      - /mnt/ceph/scratch_data:/tmp
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/ceph/jellystat_data:/backup/jellystat:ro
      - /mnt/ceph/jellyfin_data:/backup/jellyfin:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/hdd_pool/cloud/OneDrive/Storage/Eos_Backups:/archive
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 2000M
      placement:
        constraints: 
          - "node.role == manager"
      labels:
        - "shepherd.updates=true"

volumes:
  jellyfin_data:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/ceph/jellyfin_data"
      o: bind    
  jellystat-data:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/ceph/jellystat_data/jellystat"
      o: bind
  jellystat-db:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/ceph/jellystat_data/db"
      o: bind  

networks:
  jellystat:
    name: jellystat
    driver: overlay
  media:
    external: true
  outside:
    external:
      name: "host"
  local_proxy:
    external: true
    