version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Chicago
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - '/dev/shm:/config/transcodes'
      - '/mnt/ceph/jellyfin_data:/config'
      - '/mnt/samba/media:/media'
      - '/mnt/samba/cloud-storage/dropbox:/dropbox'
    networks:
      - outside
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.nvidia == true"
      labels:
        - "shepherd.updates=true"
        - docker-volume-backup.stop-during-backup=true
        - homepage.group=Media Front End
        - homepage.name=Jellyfin
        - homepage.icon=jellyfin.png
        - homepage.href=https://jellyfin.sch-apps.com
        - homepage.description=Jellyfin server
        - homepage.widget.type=jellyfin
        - homepage.widget.target=_blank
        - homepage.widget.url=https://jellyfin.sch-apps.com
        - homepage.widget.key=8001a88cdba4478d98529e6ef027d473
        - docker-volume-backup.stop-during-backup=true

  jellystat-db:
    image: postgres:15.2
    environment:
      - POSTGRES_DB=jellystat
      - POSTGRES_USER=$jellystatdb_user
      - POSTGRES_PASSWORD=$jellystatdb_password
    volumes:
    - /mnt/ceph/jellystat_data/db:/var/lib/postgresql/data
    networks:
      - jellystat
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "shepherd.updates=true"
        - docker-volume-backup.stop-during-backup=true

  jellystat:
    image: cyfershepard/jellystat:latest
    environment:
      - POSTGRES_USER=$jellystatdb_user
      - POSTGRES_PASSWORD=$jellystatdb_password
      - POSTGRES_IP=jellystat-db
      - POSTGRES_PORT=5432
      - JWT_SECRET=$jellystat_password
    ports:
      - "3002:3000"
    volumes:
      - /mnt/ceph/jellystat_data/jellystat:/app/backend/backup-data
    networks:
      - media
      - jellystat
      - local_proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jellystat-rtr.entrypoints=web"
        - "traefik.http.routers.jellystat-rtr.rule=Host(`jellystat.local.sch-apps.com`)"
        - "traefik.http.routers.jellystat-rtr.service=jellystat-svc"
        - "traefik.http.services.jellystat-svc.loadbalancer.server.port=3000"
        - "shepherd.updates=true"
        - docker-volume-backup.stop-during-backup=true

  backup:
    image: offen/docker-volume-backup:v2
    environment:
      - BACKUP_FILENAME=jellyfin-%Y-%m-%dT%H-%M-%S.tar.gz
      - BACKUP_CRON_EXPRESSION=0 7 * * * #Run at 7am UTC, 2AM CST
      - BACKUP_PRUNING_PREFIX=jellyfin-
      - BACKUP_RETENTION_DAYS=7
      - GZIP_PARALLELISM=3
    volumes:
      - /mnt/ceph/scratch_data:/tmp
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/ceph/jellystat_data:/backup/jellystat:ro
      - /mnt/ceph/jellyfin_data:/backup/jellyfin:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/samba/cloud-storage/onedrive/Eos_Backups:/archive
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 2000M
      placement:
        constraints: 
          - "node.role == manager"
      labels:
        - "shepherd.updates=true"

volumes:
  jellyfin_data:
    driver: local
  jellystat_data:
    driver: local

networks:
  jellystat:
    name: jellystat
    driver: overlay
  media:
    external: true
  outside:
    external:
      name: "host"
  local_proxy:
    external: true