version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1901:1900/udp #optional
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Chicago
      - JELLYFIN_PublishedServerUrl=192.168.6.7 #optional
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - '/mnt/ceph/jellyfin_data:/config'
      - '/mnt/samba/media:/media'
      - '/mnt/samba/cloud-storage/dropbox:/dropbox'
    networks:
      - media
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.nvidia == true"
      labels:
        - "shepherd.updates=true"

  jellystat-db:
    image: postgres:15.2
    secrets:
      - source: jellystatdb_user
        target: db_user
      - source: jellystatdb_password
        target: db_password
    environment:
      - POSTGRES_DB=jfstat
      - POSTGRES_USER=/run/secrets/db_user
      - POSTGRES_PASSWORD=/run/secrets/db_password
    volumes:
    - /mnt/ceph/jellystat_data/db:/var/lib/postgresql/data
    networks:
      - jellystat
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "shepherd.updates=true"

  jellystat:
    image: cyfershepard/jellystat:latest
    secrets:
      - source: jellystatdb_user
        target: db_user
      - source: jellystatdb_password
        target: db_password
      - source: jellystat_password
        target: user_password
    environment:
      - POSTGRES_USER=/run/secrets/db_user
      - POSTGRES_PASSWORD=/run/secrets/db_password
      - POSTGRES_IP=jellystat-db
      - POSTGRES_PORT=5432
      - JWT_SECRET=/run/secrets/user_password
    ports:
      - "3002:3000"
    volumes:
      - /mnt/ceph/jellystat_data/jellystat:/app/backend/backup-data
    networks:
      - media
      - jellystat
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "shepherd.updates=true"

volumes:
  jellyfin_data:
    driver: local
  jellystat_data:
    driver: local

secrets:
  jellystatdb_user:
    external: true
  jellystatdb_password:
    external: true
  jellystat_password:
    external: true

networks:
  jellystat:
    name: monitoring
    driver: overlay
  media:
    external: true
  proxy:
    external: true