version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1901:1900/udp #optional
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Chicago
      - JELLYFIN_PublishedServerUrl=192.168.6.7 #optional
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - '/mnt/ceph/jellyfin_data:/config'
      - '/mnt/samba/media:/media'
      - '/mnt/samba/cloud-storage/dropbox:/dropbox'
    networks:
      - media
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.nvidia == true"
      labels:
        - "shepherd.updates=true"

volumes:
  jellyfin_data:
    driver: local

networks:
  media:
    external: true
  proxy:
    external: true