version: '3'

services:
  promtail:
    image: grafana/promtail:latest
    restart: always
    container_name: promtail
    environment:
      - "TZ=America/Chicago"
    volumes:
      - '/var/lib/docker/volumes/promtail_data/promtail.yaml:/etc/promtail/docker-config.yaml'
      - '/var/lib/docker/volumes/promtail_data/positions:/positions'
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - collectors

  minecraft-exporter:
    image: joshi425/minecraft_exporter
    restart: always
    container_name: minecraft_exporter
    environment:
      - RCON_HOST=192.168.6.100
      - RCON_PORT=25575
      - RCON_PASSWORD=$rcon_password
    ports:
      - 8000:8000
    volumes:
      - /var/lib/pterodactyl/volumes/85f44477-f6be-4c6e-9b09-9a15532dad48/world:/world:ro
    networks:
      - collectors

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    restart: always
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/lib/pterodactyl/:/var/lib/pterodactyl:ro
    ports:
      - 8085:8080
    networks:
      - collectors

# Note: The you only need to set the network to allow co-existance with Pterodactyl Wings (Which uses 172.18.0.0). It is not needed otherwise.
# See here for the reasoning: https://docs.xfgn.dev/troubleshooting/pterodactyl
networks:
  collectors:
      ipam:
        driver: default
        config:
          - subnet: 172.28.0.0/16
            ip_range: 172.28.5.0/24
            gateway: 172.28.5.254
            aux_addresses:
              host1: 172.28.1.5
              host2: 172.28.1.6
              host3: 172.28.1.7