version: '3'

services:
  promtail:
    image: grafana/promtail:latest
    restart: always
    container_name: promtail
    environment:
      - "TZ=America/Chicago"
    volumes:
      - '/var/lib/docker/volumes/promtail_data/promtail.yaml:/etc/promtail/docker-config.yaml'
      - '/var/lib/docker/volumes/promtail_data/positions:/positions'
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - collectors

  telegraf:
    image: docker.io/telegraf:latest
    container_name: telegraf
    environment:
      - TZ=America/Chicago
      - HOST_OS=ubuntu
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
      - HOST_MOUNT_PREFIX=/rootfs
    volumes:
      - /var/lib/docker/volumes/telegraf_data/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    networks:
      - collectors

# Note: The you only need to set the network to allow co-existance with Pterodactyl Wings (Which uses 172.18.0.0). It is not needed otherwise.
# See here for the reasoning: https://docs.xfgn.dev/troubleshooting/pterodactyl
networks:
  collectors:
      ipam:
        driver: default
        config:
          - subnet: 172.28.0.0/16
            ip_range: 172.28.5.0/24
            gateway: 172.28.5.254
            aux_addresses:
              host1: 172.28.1.5
              host2: 172.28.1.6
              host3: 172.28.1.7