version: '3.8'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    # While host mode networking is preferred, bridge mode allows you to fully use docker swarms mesh networking capabilities
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - '/mnt/ceph/jellyfin_data:/config'
      - '/mnt/samba/media:/media'
      - '/mnt/samba/cloud-storage/dropbox:/dropbox'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.nvidia == true"
      labels:
        - "shepherd.updates=true"
      resources:
        devices:
          - driver: nvidia
            capabilities: [gpu]

volumes:
  plex_data:
    driver: local

networks:
  media: