version: '3.8'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=999
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - '/mnt/ceph/plex_data:/config'
      - '/mnt/hdd_pool/media:/ceph_media:ro'
      - '/dev/shm:/tmp'
    networks:
      - outside
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.nvidia == true"
      labels:
        - shepherd.updates=true
        - homepage.group=Media Front End
        - homepage.name=Plex
        - homepage.icon=plex.png
        - homepage.href=http://192.168.6.206:32400
        - homepage.description=Plex media server

  tautulli:
    image: ghcr.io/tautulli/tautulli
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=999
    ports:
      - 8181:8181
    volumes:
      - '/mnt/ceph/tautulli_data:/config'
    networks:
      - media
      - local_proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - traefik.enable=true
        - traefik.http.routers.tautulli-rtr.entrypoints=web
        - traefik.http.routers.tautulli-rtr.rule=Host(`tautulli.local.sch-apps.com`)
        - traefik.http.routers.tautulli-rtr.service=tautulli-svc
        - traefik.http.services.tautulli-svc.loadbalancer.server.port=8181
        - shepherd.updates=true
        - homepage.group=Media Tools
        - homepage.name=Tautulli
        - homepage.icon=tautulli.png
        - homepage.href=http://tautulli.local.sch-apps.com
        - homepage.description=Plex server stats and metrics

volumes:
  plex_data:
    driver: local
  tautulli_data:
    driver: local

networks:
  media:
    external: true
  outside:
    external:
      name: "host"
  local_proxy:
    external: true