version: '3.8'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=999
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - '/mnt/ceph/plex_data:/config'
      - '/mnt/hdd_pool/media:/ceph_media:ro'
      - '/dev/shm:/tmp'
    networks:
      - outside
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.nvidia == true"
      labels:
        - shepherd.updates=true
        - homepage.group=Media Front End
        - homepage.name=Plex
        - homepage.icon=plex.png
        - homepage.href=http://192.168.6.206:32400
        - homepage.description=Plex media server
        - docker-volume-backup.stop-during-backup=plex_backup

  tautulli:
    image: ghcr.io/tautulli/tautulli
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=999
    ports:
      - 8181:8181
    volumes:
      - '/mnt/ceph/tautulli_data:/config'
    networks:
      - media
      - local_proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - traefik.enable=true
        - traefik.http.routers.tautulli-rtr.entrypoints=web
        - traefik.http.routers.tautulli-rtr.rule=Host(`tautulli.local.sch-apps.com`)
        - traefik.http.routers.tautulli-rtr.service=tautulli-svc
        - traefik.http.services.tautulli-svc.loadbalancer.server.port=8181
        - shepherd.updates=true
        - homepage.group=Media Tools
        - homepage.name=Tautulli
        - homepage.icon=tautulli.png
        - homepage.href=http://tautulli.local.sch-apps.com
        - homepage.description=Plex server stats and metrics
        - docker-volume-backup.stop-during-backup=plex_backup

  backup:
    image: offen/docker-volume-backup:v2
    environment:
      - BACKUP_FILENAME=plex-%Y-%m-%dT%H-%M-%S.tar.gz
      - BACKUP_CRON_EXPRESSION=0 7 * * * #Run at 7am UTC, 2AM CST
      - BACKUP_PRUNING_PREFIX=plex-
      - BACKUP_RETENTION_DAYS=5
      - GZIP_PARALLELISM=3
      - BACKUP_STOP_DURING_BACKUP_LABEL=plex_backup
    volumes:
      - /mnt/ceph/scratch_data:/tmp
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/ceph/tautulli_data:/backup/tautulli:ro
      - /mnt/ceph/plex_data:/backup/plex:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/hdd_pool/cloud/B2/eos:/archive
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 2000M
      placement:
        constraints: 
          - "node.role == manager"
      labels:
        - "shepherd.updates=true"

volumes:
  plex_data:
    driver: local
  tautulli_data:
    driver: local

networks:
  media:
    external: true
  outside:
    external:
      name: "host"
  local_proxy:
    external: true