version: '3.8'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=999
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    # While host mode networking is preferred, bridge mode allows you to fully use docker swarms mesh networking capabilities
    volumes:
      - '/mnt/ceph/plex_data:/config'
      - '/mnt/samba/media:/media'
      - '/mnt/samba/cloud-storage/dropbox:/dropbox'
    networks:
      - outside
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.nvidia == true"
          - "node.hostname == sovereign-01"
      labels:
        - "shepherd.updates=true"

  tautulli:
    image: ghcr.io/tautulli/tautulli
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=999
    ports:
      - 8181:8181
    volumes:
      - '/mnt/ceph/tautulli_data:/config'
    networks:
      - media
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "shepherd.updates=true"

volumes:
  plex_data:
    driver: local
  tautulli_data:
    driver: local

networks:
  media:
    external: true
  outside:
    external:
      name: "host"