version: "3.8"

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      # These ports are in format <host-port>:<container-port>
      - '81:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '82:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    # Uncomment the next line if you uncomment anything in the section
    environment:
      # Uncomment this if you want to change the location of 
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
    volumes:
      - '/mnt/ceph/npm_data/npm:/data'
      - '/mnt/ceph/npm_data/npm-letsencrypt:/etc/letsencrypt'
    restart: always
    networks:
      - external_proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
          - "shepherd.updates=true"

volumes:
  npm_data:
    driver: local

networks:
  external_proxy:
    name: external_proxy
    driver: overlay
    attachable: true