version: '3.8'

services:
  arch-krusader:
    image: binhex/arch-krusader
    environment:
      - TEMP_FOLDER=/config/krusader/tmp
      - WEBPAGE_TITLE=Eos Swarm
      - VNC_PASSWORD=krusaderadm
      - UMASK=1000
      - PUID=1000
      - PGID=999
    ports:
      - '5900:5900'
      - '6080:6080'
    volumes:
      - '/mnt/ceph/krusader_data:/config'
      - '/etc/localtime:/etc/localtime:ro'
      - '/mnt/ceph:/data/docker_volumes'
      - '/mnt/samba:/data/samba'
    networks:
      - local_proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
          - "node.labels.host_type == proxmox"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.krusader-rtr.entrypoints=web"
        - "traefik.http.routers.krusader-rtr.rule=Host(`krusader.local.sch-apps.com`)"
        - "traefik.http.routers.krusader-rtr.service=krusader-svc"
        - "traefik.http.services.krusader-svc.loadbalancer.server.port=6080"
        - "shepherd.updates=true"

  filebrowser:
    image: hurlenko/filebrowser
    environment:
      - FB_BASEURL=/filebrowser
      - PUID=1000
      - PGID=999
    ports:
      - 4433:8080
    volumes:
      - '/mnt/ceph/filebrowser_data:/config'
      - '/mnt/ceph:/data/docker_volumes'
    networks:
      - local_proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
          - "node.labels.host_type == proxmox"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.filebrowser-rtr.entrypoints=web"
        - "traefik.http.routers.filebrowser-rtr.rule=Host(`filebrowser.local.sch-apps.com`)"
        - "traefik.http.routers.filebrowser-rtr.service=filebrowser-svc"
        - "traefik.http.services.filebrowser-svc.loadbalancer.server.port=8080"
        - "shepherd.updates=true"

volumes:
  krusader_data:
    driver: local
  filebrowser_data:
    driver: local

networks:
  local_proxy:
    external: true
  