version: '3.8'

services:
  arch-krusader:
    image: binhex/arch-krusader
    environment:
      - TEMP_FOLDER=/config/krusader/tmp
      - WEBPAGE_TITLE=Eos Swarm
      - VNC_PASSWORD=krusaderadm
      - UMASK=1000
      - PUID=0
      - PGID=0
    ports:
      - '5900:5900'
      - '6080:6080'
    volumes:
      - '/var/lib/docker/volumes/krusader:/config'
      - '/etc/localtime:/etc/localtime:ro'
      - /var/lib/docker/volumes:/data/docker_volumes
      - disk-imports:/data/disk-imports
      - dropbox:/data/dropbox
      - onedrive:/data/onedrive
      - downloads:/data/downloads
      - temp:/data/temp
      - donn-movies:/data/donn-movies
      - donn-tvshows:/data/donn-tvshows

  filebrowser:
    image: hurlenko/filebrowser
    environment:
      - FB_BASEURL=/filebrowser
      - PUID=1000
      - PGID=1000
    ports:
      - 4433:8080
    volumes:
      - '/var/lib/docker/volumes/filebrowser:/config'
      - /var/lib/docker/volumes:/data/docker_volumes