version: '3.8'

services:
  arch-krusader:
    image: binhex/arch-krusader
    environment:
      - TEMP_FOLDER=/config/krusader/tmp
      - WEBPAGE_TITLE=Eos Swarm
      - VNC_PASSWORD=krusaderadm
      - UMASK=1000
      - PUID=1000
      - PGID=999
    ports:
      - '5900:5900'
      - '6080:6080'
    volumes:
      - '/mnt/ceph/krusader_data:/config'
      - '/etc/localtime:/etc/localtime:ro'
      - '/mnt/ceph:/data/docker_volumes'
      - '/mnt/samba/media:/data/media'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "shepherd.updates=true"

  filebrowser:
    image: hurlenko/filebrowser
    environment:
      - FB_BASEURL=/filebrowser
      - PUID=1000
      - PGID=999
    ports:
      - 4433:8080
    volumes:
      - '/mnt/ceph/filebrowser_data:/config'
      - '/mnt/ceph:/data/docker_volumes'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "shepherd.updates=true"

volumes:
  krusader_data:
    driver: local
  filebrowser_data:
    driver: local