---
- name: Create ffmpeg-api Prod Deployment
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ffmpeg-api
        namespace: jovian-prod
      spec:
        progressDeadlineSeconds: 600
        replicas: 1
        revisionHistoryLimit: 3
        selector:
          matchLabels:
            app: ffmpeg-api
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              app: ffmpeg-api
          spec:
            containers:
            - name: ffmpeg-api
              image: msuarezpumpun/ffmpeg-api:master
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 3000
                name: ffmpeg-http
                protocol: TCP      
              volumeMounts:
              - name: smb-media
                mountPath: /media
                readOnly: false
              - name: smb-dropbox
                mountPath: /dropbox
                readOnly: false
              env:
              - name: TZ
                value: 'America/Chicago'
              - name: PUID
                value: '1000'
              - name: PGID
                value: '1000'
            volumes:
            - name: smb-media
              persistentVolumeClaim:
                claimName: ffmpeg-api-smb-media-pvc
                readOnly: false
            - name: smb-dropbox
              persistentVolumeClaim:
                claimName: ffmpeg-api-external-smb-pvc
                readOnly: false

- name: Create ffmpeg-api Service
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: service
      metadata:
        name: ffmpeg-api-service
        namespace: jovian-prod
      spec:
        selector:
          app: ffmpeg-api
        ports:
          - port: 3000
            targetPort: ffmpeg-http
            protocol: TCP
            name: ffmpeg-http

- name: Create ffmpeg-api Ingress
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: ffmpeg-api-ingress
        namespace: jovian-prod
        annotations:
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
      spec:
        rules:
          - host: ffmpeg-api.jovian.local.sch-apps.com
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name:  ffmpeg-api-service
                      port:
                        number: 3000

# https://github.com/kubernetes-csi/csi-driver-smb/blob/master/deploy/example/e2e_usage.md#option2-pvpvc-usage
- name: Create the ffmpeg-api SMB PV
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        annotations:
          pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
        name: ffmpeg-api-smb-media
      spec:
        capacity:
          storage: 72Ti
        accessModes:
          - ReadWriteMany
        persistentVolumeReclaimPolicy: Retain
        storageClassName: smb-csi-media
        mountOptions:
          - dir_mode=0777
          - file_mode=0777
        csi:
          driver: smb.csi.k8s.io
          # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
          # make sure this value is unique for every share in the cluster
          volumeHandle: 192.168.100.162/media
          volumeAttributes:
            source: //192.168.100.162/media
          nodeStageSecretRef:
            name: smb-media-manangers
            namespace: jovian-prod

- name: Create ffmpeg-api SMB PVC
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: ffmpeg-api-smb-media-pvc
        namespace: jovian-prod
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: smb-csi-media
        resources:
          requests:
            storage: 72Ti
        volumeName: ffmpeg-api-smb-media

# Syn-Coruscant
# https://github.com/kubernetes-csi/csi-driver-smb/blob/master/deploy/example/e2e_usage.md#option2-pvpvc-usage
- name: Create the Syn-Coruscant SMB PV
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        annotations:
          pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
        name: ffmpeg-api-external-smb
      spec:
        capacity:
          storage: 5Ti
        accessModes:
          - ReadWriteMany
        persistentVolumeReclaimPolicy: Retain
        storageClassName: smb-csi-ffmpeg-api-syn
        mountOptions:
          - dir_mode=0777
          - file_mode=0777
        csi:
          driver: smb.csi.k8s.io
          # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
          # make sure this value is unique for every share in the cluster
          volumeHandle: 192.168.100.42/Dropbox
          volumeAttributes:
            source: //192.168.100.42/Dropbox
          nodeStageSecretRef:
            name: smb-syn-immich
            namespace: jovian-prod

- name: Create ffmpeg-api Syn-Coruscant SMB PVC
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: ffmpeg-api-external-smb-pvc
        namespace: jovian-prod
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: smb-csi-ffmpeg-api-syn
        resources:
          requests:
            storage: 5Ti
        volumeName: ffmpeg-api-external-smb
