version: '3.8'

services:
  telegraf-standard:
    image: telegraf
    environment:
      - "TZ=America/Chicago"
    hostname: "{{.Node.Hostname}}"
    volumes:
    - '/mnt/ceph/telegraf_data/standard/telegraf.conf:/etc/telegraf/telegraf.conf:ro'
    - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: global
      labels:
        - "shepherd.updates=true"
      placement:
        constraints: 
          - "node.labels.nvidia != true"
    networks:
      - monitoring

  telegraf-gpu:
    image: telegraf
    environment:
      - "TZ=America/Chicago"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=utility
    hostname: "{{.Node.Hostname}}"
    volumes:
    - '/mnt/ceph/telegraf_data/gpu/telegraf.conf:/etc/telegraf/telegraf.conf:ro'
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /usr/bin/nvidia-smi:/usr/bin/nvidia-smi:ro
    deploy:
      mode: global
      labels:
        - "shepherd.updates=true"
      placement:
        constraints: 
          - "node.labels.nvidia == true"
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    environment:
      - "TZ=America/Chicago"
    volumes:
      - '/mnt/ceph/promtail_data/promtail.yaml:/etc/promtail/docker-config.yaml:ro'
      - '/mnt/ceph/promtail_data/positions:/positions'
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/var/log:ro
    command: -config.file=/etc/promtail/docker-config.yaml
    deploy:
      mode: global
      labels:
        - "shepherd.updates=true"
    networks:
      - monitoring

  unpoller:
    image: ghcr.io/unpoller/unpoller:latest
    secrets:
      - source: unifi_user
        target: ui_user
      - source: unifi_pass
        target: ui_pass
      - source: unpoller_influxdb_user
        target: influx_user
      - source: unpoller_influxdb_pass
        target: influx_pass
      - source: unpoller_influxdb
        target: influx_db
    environment:
      - UP_INFLUXDB_DB=/run/secrets/influx_db
      - UP_INFLUXDB_USER=/run/secrets/influx_user
      - UP_INFLUXDB_PASS=/run/secrets/influx_pass
      - UP_INFLUXDB_BUCKET=autogen
      - UP_INFLUXDB_URL=observability_influxdb
      - UP_UNIFI_DEFAULT_USER=/run/secrets/ui_user
      - UP_UNIFI_DEFAULT_PASS=/run/secrets/ui_pass
      - UP_UNIFI_DEFAULT_URL=https://192.168.6.1
      - UP_POLLER_DEBUG=false
      - UP_UNIFI_DEFAULT_SAVE_DPI=false
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "shepherd.updates=true"
    networks:
      - monitoring

volumes:
  telegraf_data:
    driver: local
  promtail_data:
    driver: local

secrets:
  unifi_user:
    external: true
  unifi_pass:
    external: true
  unpoller_influxdb:
    external: true
  unpoller_influxdb_user:
    external: true
  unpoller_influxdb_pass:
    external: true

networks:
  monitoring:
    external: true