version: '3.8'

services:
  telegraf:
    image: telegraf
    volumes:
    - '/mnt/ceph/telegraf_data/telegraf.conf:/etc/telegraf/telegraf.conf:ro'
    - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
    - '8125:8125'
    deploy:
      mode: global
      labels:
        - "shepherd.updates=true"
    networks:
      - monitoring

volumes:
  telegraf_data:
    driver: local

networks:
  monitoring:
    external: true