version: '3.8'

services:
  telegraf:
    image: telegraf
    hostname: "{{.Node.Hostname}}"
    volumes:
    - '/mnt/ceph/telegraf_data/telegraf.conf:/etc/telegraf/telegraf.conf:ro'
    - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
    - '8125:8125'
    deploy:
      mode: global
      labels:
        - "shepherd.updates=true"
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    volumes:
      - '/mnt/ceph/promtail_data/promtail.yaml:/etc/promtail/docker-config.yaml'
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/docker-config.yaml
    deploy:
      mode: global
      labels:
        - "shepherd.updates=true"
    networks:
      - monitoring

volumes:
  telegraf_data:
    driver: local
  promtail_data:
    driver: local

networks:
  monitoring:
    external: true