pve:
  hosts:
    pve-eos-01:
      ansible_host: 192.168.6.30
    pve-eos-02:
      ansible_host: 192.168.6.31
    pve-eos-03:
      ansible_host: 192.168.6.32
vms:
  children:
    samba-hosts:
      children:
        ubuntu-noble:
          hosts:
            zion:
              ansible_host: 192.168.6.190
    guests:
      children:
        julius:
          hosts:
            lunaland:
              ansible_host: 192.168.100.109

    cloud-hosts:
      children:
        ubuntu-noble:
          hosts:
            pegasus:
              ansible_host: 192.168.6.170
    docker:
      children:
        standalone:
          hosts:
            wing-commander:
              ansible_host: 192.168.6.90
            polaris:
              ansible_host: 192.168.6.195
        pterodactyl:
          hosts:
            jurassic-park-01:
              ansible_host: 192.168.6.100
            jurassic-park-02:
              ansible_host: 192.168.6.101
        swarm:
          children:
            managers:
              hosts:
                starbase-01: 
                  ansible_host: 192.168.6.40
                starbase-02: 
                  ansible_host: 192.168.6.41
                starbase-03: 
                  ansible_host: 192.168.6.42
            workers:
              children:
                gpu:
                  hosts:
                    sovereign-01: 
                      ansible_host: 192.168.6.50
                    sovereign-02: 
                      ansible_host: 192.168.6.51
                    sovereign-03: 
                      ansible_host: 192.168.6.52
                vpn:
                  hosts:
                    defiant-01: 
                      ansible_host: 192.168.27.60
                    defiant-02: 
                      ansible_host: 192.168.27.61
                wan2:
                  hosts:
                    excelsior-01: 
                      ansible_host: 192.168.11.10
                    excelsior-02: 
                      ansible_host: 192.168.11.11
