version: '3.8'

services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Chicago
    volumes:
      - /mnt/ceph/freshrss_data:/config
    ports:
      - 8090:80
    networks:
      - local_proxy
      - cftunnel
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - traefik.enable=true
        - traefik.http.routers.freshrss-rtr.entrypoints=web
        - traefik.http.routers.freshrss-rtr.rule=Host(`freshrss.local.sch-apps.com`)
        - traefik.http.routers.freshrss-rtr.service=freshrss-svc
        - traefik.http.services.freshrss-svc.loadbalancer.server.port=80
        - shepherd.updates=true
        - docker-volume-backup.stop-during-backup=true
        - homepage.group=Media Front End
        - homepage.name=freshrss
        - homepage.icon=freshrss.png
        - homepage.href=http://freshrss.local.sch-apps.com
        - homepage.description=Reads and feeds
        - homepage.widget.type=freshrss
        - homepage.widget.target=_blank
        - homepage.widget.url=http://freshrss.local.sch-apps.com
        - homepage.widget.username=$username
        - homepage.widget.password=$password

  backup:
    image: offen/docker-volume-backup:v2
    environment:
      - BACKUP_FILENAME=freshrss-%Y-%m-%dT%H-%M-%S.tar.gz
      - BACKUP_CRON_EXPRESSION=10 7 * * * #Run at 7:10am UTC, 2:10AM CST
      - BACKUP_PRUNING_PREFIX=freshrss-
      - BACKUP_RETENTION_DAYS=7
      - GZIP_PARALLELISM=3
    volumes:
      - /dev/shm:/tmp
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/ceph/freshrss_data:/backup/freshrss:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/samba/cloud-storage/onedrive/Eos_Backups:/archive
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 1000M
      placement:
        constraints: 
          - "node.role == manager"
      labels:
        - "shepherd.updates=true"

volumes:
  freshrss_data:
    driver: local

networks:
  local_proxy:
    external: true
  cftunnel:
    external: true