version: '3.8'

services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Chicago
    volumes:
      - /mnt/ceph/freshrss_data:/config
    ports:
      - 8090:80
    networks:
      - local_proxy
      - cftunnel
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.freshrss-rtr.entrypoints=web"
        - "traefik.http.routers.freshrss-rtr.rule=Host(`freshrss.local.sch-apps.com`)"
        - "traefik.http.routers.freshrss-rtr.service=freshrss-svc"
        - "traefik.http.services.freshrss-svc.loadbalancer.server.port=80"
        - "shepherd.updates=true"

volumes:
  freshrss_data:
    driver: local

networks:
  local_proxy:
    external: true
  cftunnel:
    external: true