version: '3.8'

services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Chicago
    volumes:
      - /mnt/ceph/freshrss_data:/config
    ports:
      - 8090:80
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "shepherd.updates=true"

volumes:
  freshrss_data:
    driver: local

networks:
  proxy:
    external: true
  cftunnel:
    external: true