---
- name: Set up Docker data folders
  hosts: starbase-01
  remote_user: ansible
  become: true

  tasks:
    - name: Create docker volumes
      ansible.builtin.file:
        path: /mnt/ceph/{{ item }}
        state: directory
        recurse: yes
        owner: ansible
        group: docker
        mode: '0755'
      loop:
        - portainer_data
        - npm_data/npm
        - npm_data/npm-letsencrypt
        - influxdb_data
        - chronograf_data
        - loki_data
        - telegraf_data
        - promtail_data
        - promtail_data/positions
        - folding_at_home/node1
        - folding_at_home/node2
        - folding_at_home/node3
        - jellyfin_data
        - overseerr_data
        - jellyseerr_data
        - prowlarr_data
        - bazarr_data
        - sonarr_data
        - radarr_data
        - qbittorrent_data

    - name: Create docker volumes with insecure permissions
      ansible.builtin.file:
        path: /mnt/ceph/{{ item }}
        state: directory
        recurse: yes
        owner: ansible
        group: docker
        mode: '1777'
      loop:
        - grafana_data