---
- name: Set up Docker data folders
  hosts: starbase-01
  remote_user: ansible
  become: true

  tasks:
    - name: Create docker volumes
      ansible.builtin.file:
        path: /mnt/ceph/{{ item }}
        state: directory
        recurse: yes
        owner: ansible
        group: docker
        mode: '0755'
      loop:
        - portainer_data
        - npm_data/npm
        - npm_data/npm-letsencrypt
        - influxdb_data
        - chronograf_data
        - loki_data

    - name: Create docker volumes with insecure permissions
      ansible.builtin.file:
        path: /mnt/ceph/{{ item }}
        state: directory
        recurse: yes
        owner: ansible
        group: docker
        mode: '1777'
      loop:
        - grafana_data