# To run:
# ansible-playbook playbooks/install_keepalived.yaml -i inventories/eos.yaml --become-password-file=credentials/ansible_password.txt
- name: Install keepalived on the manager nodes
  hosts: pihole, managers, gpu
  remote_user: ansible
  become: true

  tasks:
    - name: Update and upgrade all packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Install the keepalived package
      ansible.builtin.apt:
        pkg:
          - keepalived

    - name: Create the keepalived config file
      ansible.builtin.file:
        path: /etc/keepalived/keepalived.conf
        state: touch

    - name: Create the directory for keepalived's scripts
      ansible.builtin.file:
        path: /usr/libexec/keepalived
        state: directory
        mode: '0755'
