# To run:
# ansible-playbook playbooks/qemu_guest_agent.yaml -i inventories/eos.yaml --become-password-file=credentials/ansible_eos_password.txt
# ansible-playbook playbooks/qemu_guest_agent.yaml -i inventories/andromeda.yaml --become-password-file=credentials/ansible_andromeda_password.txt
- name: Set up the Qemu Guest Agent
  hosts: swarm
  remote_user: ansible
  become: true

  tasks:
    - name: Update and upgrade all packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Install the Qemu Guest Agent package
      ansible.builtin.apt:
        pkg:
          - qemu-guest-agent

    - name: Start the service, if not started
      ansible.builtin.systemd_service:
        name: qemu-guest-agent
        state: started
    