---

curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | \
   sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg \
   --dearmor

sudo apt-get install -y mongodb-org=7.0.15 mongodb-org-database=7.0.15 mongodb-org-server=7.0.15 mongodb-mongosh mongodb-org-mongos=7.0.15 mongodb-org-tools=7.0.15

Datanode sha2 = bt8Ho237rGhZblZ6q5pFJm-dkZKLYFIcK8ba9pj-GWcpO3P3D7KlkcFOzfVjOBzLL034RBLU8nO-oNU-wcOw55DXFIo75fTe

GLT@918Dream IL

root password sha2 = 6a2a8078fa4c83ed177b86a03dc502cbd9b742768b58afe5a1a8d556096783bb

sudo sed -i 's/#http_bind_address = 127.0.0.1.*/http_bind_address = 192.168.6.140:9000/g' /etc/graylog/server/server.conf