---
- name: Create Bazarr Deployment
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: bazarr
        namespace: jovian-prod
        labels:
          app: bazarr
          service: media-backend
      spec:
        progressDeadlineSeconds: 600
        replicas: 1
        revisionHistoryLimit: 3
        selector:
          matchLabels:
            app: bazarr
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              app: bazarr
          spec:
            nodeSelector:
              connection: vpn
            containers:
            - name: bazarr
              image: ghcr.io/hotio/bazarr:latest
              imagePullPolicy: Always
              ports:
              - containerPort: 6767
                name: bazarr-http
                protocol: TCP   
              volumeMounts:
              - name: config
                mountPath: /config
              env:
              - name: TZ
                value: 'America/Chicago'
              - name: PUID
                value: '1000'
              - name: PGID
                value: '1000'
              - name: UMASK
                value: '002'
            volumes:
            - name: config
              persistentVolumeClaim:
                claimName: bazarr-pvc
                readOnly: false

- name: Create Bazarr Service
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: service
      metadata:
        name: bazarr-service
        namespace: jovian-prod
      spec:
        selector:
          app: bazarr
        ports:
          - port: 6767
            targetPort: bazarr-http
            protocol: TCP
            name: bazarr-http

- name: Create Bazarr Ingress
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: bazarr-ingress
        namespace: jovian-prod
      spec:
        rules:
          - host: bazarr.jovian.local.sch-apps.com
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name:  bazarr-service
                      port:
                        number: 6767

- name: Create Bazarr PVC
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: bazarr-pvc
        namespace: jovian-prod
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: k8s-cephfs
        resources:
          requests:
            storage: 5Gi
