---
- name: Create grafana Deployment
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: grafana
        namespace: jovian-prod
        labels:
          app: grafana
          service: observability
      spec:
        progressDeadlineSeconds: 600
        replicas: 1
        revisionHistoryLimit: 3
        selector:
          matchLabels:
            app: grafana
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              app: grafana
          spec:
            nodeSelector:
              connection: standard
            securityContext:
              runAsUser: 472
              fsGroup: 472
            containers:
            - name: grafana
              image: grafana/grafana-oss
              imagePullPolicy: Always
              ports:
              - containerPort: 3000
                name: grafana-http
                protocol: TCP   
              volumeMounts:
              - name: config
                mountPath: /var/lib/grafana
              env:
              - name: TZ
                value: 'America/Chicago'
            volumes:
            - name: config
              persistentVolumeClaim:
                claimName: grafana-pvc
                readOnly: false

- name: Create grafana Service
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: service
      metadata:
        name: grafana-service
        namespace: jovian-prod
      spec:
        selector:
          app: grafana
        ports:
          - port: 3000
            targetPort: grafana-http
            protocol: TCP
            name: grafana-http

- name: Create grafana Ingress
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: grafana-ingress
        namespace: jovian-prod
      spec:
        rules:
          - host: grafana.jovian.local.sch-apps.com
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name:  grafana-service
                      port:
                        number: 3000

- name: Create grafana PVC
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: grafana-pvc
        namespace: jovian-prod
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: k8s-cephfs
        resources:
          requests:
            storage: 1Gi