---
- name: Create grafana Deployment
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: grafana
        namespace: jovian-prod
        labels:
          app: grafana
          service: observability
      spec:
        progressDeadlineSeconds: 600
        replicas: 1
        revisionHistoryLimit: 3
        selector:
          matchLabels:
            app: grafana
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              app: grafana
          spec:
            nodeSelector:
              connection: standard
            securityContext:
              runAsUser: 472
              fsGroup: 472
            containers:
            - name: grafana
              image: grafana/grafana-oss
              imagePullPolicy: Always
              ports:
              - containerPort: 3000
                name: grafana-http
                protocol: TCP   
              volumeMounts:
              - name: config
                mountPath: /var/lib/grafana
              env:
              - name: TZ
                value: 'America/Chicago'
            volumes:
            - name: config
              persistentVolumeClaim:
                claimName: grafana-pvc
                readOnly: false

- name: Create grafana Service
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: service
      metadata:
        name: grafana-service
        namespace: jovian-prod
      spec:
        selector:
          app: grafana
        ports:
          - port: 3000
            targetPort: grafana-http
            protocol: TCP
            name: grafana-http

- name: Create grafana Ingress
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: grafana-ingress
        namespace: jovian-prod
      spec:
        rules:
          - host: grafana.jovian.local.sch-apps.com
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name:  grafana-service
                      port:
                        number: 3000

- name: Create grafana PVC
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: grafana-pvc
        namespace: jovian-prod
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: k8s-cephfs
        resources:
          requests:
            storage: 1Gi

- name: Create Grafana Backup schedule
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      metadata:
        name: grafana-backup
        namespace: jovian-prod
      spec:
        # The PVC to be backed up
        sourcePVC: grafana-pvc
        trigger:
          # Take a backup every day at 2am
          schedule: "0 2 * * *"
        restic:
          # Prune the repository (repack to free space) every 2 weeks
          pruneIntervalDays: 14
          # Name of the Secret with the connection information
          repository: restic-grafana
          # Retention policy for backups
          retain:
            daily: 7
          # Snapshot the source volume prior to taking a backup to ensure a point-in-time image.
          copyMethod: Snapshot
          volumeSnapshotClassName: csi-cephfsplugin-snapclass
