---
- name: Create openspeedtest Deployment
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: openspeedtest
        namespace: jovian-prod
        labels:
          app: openspeedtest
          service: networking
      spec:
        progressDeadlineSeconds: 600
        replicas: 1
        revisionHistoryLimit: 3
        selector:
          matchLabels:
            app: openspeedtest
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              app: openspeedtest
          spec:
            nodeSelector:
              connection: standard
            containers:
            - name: openspeedtest
              image: openspeedtest/latest
              imagePullPolicy: Always
              ports:
              - containerPort: 3000
                name: http
              - containerPort: 3001
                name: https

- name: Create openspeedtest LB Service
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: service
      metadata:
        name: openspeedtest-service
        namespace: jovian-prod
        annotations:
          metallb.io/address-pool: prod-pool
          metallb.io/loadBalancerIPs: 192.168.6.211
      spec:
        externalTrafficPolicy: Local
        ports:
        - port: 80
          targetPort: http
          name: http
        - port: 443
          targetPort: https
          name: https
        selector:
          app: openspeedtest
        type: LoadBalancer
