---
- name: Create Radarr Deployment
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: radarr
        namespace: jovian-prod
        labels:
          app: radarr
          service: media-backend
      spec:
        progressDeadlineSeconds: 600
        replicas: 1
        revisionHistoryLimit: 3
        selector:
          matchLabels:
            app: radarr
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              app: radarr
          spec:
            nodeSelector:
              connection: vpn
            containers:
            - name: radarr
              image: ghcr.io/hotio/radarr:latest
              imagePullPolicy: Always
              ports:
              - containerPort: 7878
                name: radarr-http
                protocol: TCP   
              volumeMounts:
              - name: config
                mountPath: /config
              env:
              - name: TZ
                value: 'America/Chicago'
              - name: PUID
                value: '1000'
              - name: PGID
                value: '1000'
              - name: UMASK
                value: '002'
            volumes:
            - name: config
              persistentVolumeClaim:
                claimName: radarr-pvc
                readOnly: false

- name: Create Radarr Service
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: service
      metadata:
        name: radarr-service
        namespace: jovian-prod
      spec:
        selector:
          app: radarr
        ports:
          - port: 7878
            targetPort: radarr-http
            protocol: TCP
            name: radarr-http

- name: Create Radarr Ingress
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: radarr-ingress
        namespace: jovian-prod
      spec:
        rules:
          - host: radarr.jovian.local.sch-apps.com
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name:  radarr-service
                      port:
                        number: 7878

- name: Create Radarr PVC
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: radarr-pvc
        namespace: jovian-prod
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: k8s-cephfs
        resources:
          requests:
            storage: 5Gi
