---
- name: Create Sonarr Deployment
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: sonarr
        namespace: jovian-prod
        labels:
          app: sonarr
          service: media-backend
      spec:
        progressDeadlineSeconds: 600
        replicas: 1
        revisionHistoryLimit: 3
        selector:
          matchLabels:
            app: sonarr
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              app: sonarr
          spec:
            nodeSelector:
              connection: vpn
            containers:
            - name: sonarr
              image: ghcr.io/hotio/sonarr:latest
              imagePullPolicy: Always
              ports:
              - containerPort: 8989
                name: sonarr-http
                protocol: TCP   
              volumeMounts:
              - name: config
                mountPath: /config
              env:
              - name: TZ
                value: 'America/Chicago'
              - name: PUID
                value: '1000'
              - name: PGID
                value: '1000'
              - name: UMASK
                value: '002'
            volumes:
            - name: config
              persistentVolumeClaim:
                claimName: sonarr-pvc
                readOnly: false

- name: Create Sonarr Service
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: service
      metadata:
        name: sonarr-service
        namespace: jovian-prod
      spec:
        selector:
          app: sonarr
        ports:
          - port: 8989
            targetPort: sonarr-http
            protocol: TCP
            name: sonarr-http

- name: Create Sonarr Ingress
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: sonarr-ingress
        namespace: jovian-prod
      spec:
        rules:
          - host: sonarr.jovian.local.sch-apps.com
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name:  sonarr-service
                      port:
                        number: 8989

- name: Create Sonarr PVC
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: sonarr-pvc
        namespace: jovian-prod
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: k8s-cephfs
        resources:
          requests:
            storage: 5Gi
