---
- name: Create tautulli Deployment
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: tautulli
        namespace: jovian-prod
        labels:
          app: tautulli
          service: media-backend
      spec:
        progressDeadlineSeconds: 600
        replicas: 1
        revisionHistoryLimit: 3
        selector:
          matchLabels:
            app: tautulli
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              app: tautulli
          spec:
            containers:
            - name: tautulli
              image: ghcr.io/tautulli/tautulli:latest
              imagePullPolicy: Always
              ports:
              - containerPort: 8181
                name: tautulli-http
                protocol: TCP
              volumeMounts:
              - name: config
                mountPath: /config
              env:
              - name: TZ
                value: 'America/Chicago'
              - name: PUID
                value: '1000'
              - name: PGID
                value: '1000'
            volumes:
            - name: config
              persistentVolumeClaim:
                claimName: tautulli-pvc
                readOnly: false

- name: Create tautulli Service
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: service
      metadata:
        name: tautulli-service
        namespace: jovian-prod
      spec:
        selector:
          app: tautulli
        ports:
          - port: 8181
            targetPort: tautulli-http
            protocol: TCP
            name: tautulli-http

- name: Create tautulli Ingress
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: tautulli-ingress
        namespace: jovian-prod
      spec:
        rules:
          - host: tautulli.jovian.local.sch-apps.com
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name:  tautulli-service
                      port:
                        number: 8181

- name: Create tautulli PVC
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: tautulli-pvc
        namespace: jovian-prod
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: k8s-cephfs
        resources:
          requests:
            storage: 10Gi
