version: '3.8'

services:
  database:
    image: mariadb:10.5
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - pterodactyl
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - shepherd.updates=true

  cache:
    image: redis:alpine
    networks:
      - pterodactyl
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - shepherd.updates=true

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    #ports:
    #  - "80:80"
    #  - "443:443"
    environment:
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      APP_SERVICE_AUTHOR: $APP_SERVICE_AUTHOR
      APP_URL: $APP_URL
      APP_TIMEZONE: "America/Chicago"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      REDIS_PORT: 6379
      MAIL_FROM: $MAIL_FROM
      MAIL_DRIVER: "smtp"
      MAIL_HOST: "smtp.gmail.com"
      MAIL_PORT: "587"
      MAIL_USERNAME: $MAIL_USERNAME
      MAIL_PASSWORD: $MAIL_PASSWORD
      MAIL_ENCRYPTION: “true”
      APP_DEBUG: “false”
      TRUSTED_PROXIES: $TRUSTED_PROXIES
      DB_HOST: "database"
      DB_PORT: 3306
      DB_USER: $MYSQL_USER
      DB_PASSWORD: $MYSQL_PASSWORD
      DB_DATABASE: $MYSQL_DATABASE
    networks:
      - local_proxy
      - pterodactyl
      - cftunnel
    volumes:
      - var:/app/var/
      - nginx:/etc/nginx/http.d/
      - certs:/etc/letsencrypt/
      - logs:/app/storage/logs
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - traefik.enable=true
        - traefik.http.routers.pterodactyl-rtr.entrypoints=web
        - traefik.http.routers.pterodactyl-rtr.rule=Host(`pterodactyl.local.sch-apps.com`)
        - traefik.http.routers.pterodactyl-rtr.service=pterodactyl-svc
        - traefik.http.services.pterodactyl-svc.loadbalancer.server.port=80
        - homepage.group=Other
        - homepage.name=Pterodactyl Panel
        - homepage.icon=pterodactyl.png
        - homepage.href=http://pterodactyl.local.sch-apps.com
        - homepage.description=Game server management
        - shepherd.updates=true

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/ceph/pterodactyl_data/db"
      o: bind
  var:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/ceph/pterodactyl_data/panel/var"
      o: bind
  nginx:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/ceph/pterodactyl_data/panel/nginx"
      o: bind
  certs:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/ceph/pterodactyl_data/panel/certs"
      o: bind
  logs:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/ceph/pterodactyl_data/panel/logs"
      o: bind

networks:
  pterodactyl:
    name: pterodactyl
    driver: overlay
  local_proxy:
    external: true
  cftunnel:
    external: true
