version: '3.8'

services:
  wings:
    image: ghcr.io/pterodactyl/wings:latest
    restart: always
    container_name: wings
    networks:
      - wings0
    privileged: true

    ports:
      - "9443:9443"
      - "3022:3022"
    tty: true
    environment:
      TZ: "America/Chicago"
      WINGS_UID: 1000
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/etc/pterodactyl/:/etc/pterodactyl/"
      - "/var/lib/pterodactyl/:/var/lib/pterodactyl/"
      - "/var/log/pterodactyl/:/var/log/pterodactyl/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
      - "/etc/letsencrypt/:/etc/letsencrypt/"
      - "/tmp/:/tmp/"
      - "/mnt/hdd_pool/backups/pterodactyl/JP02/:/mnt/hdd_pool/backups/pterodactyl/JP02/"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  wings0:
    name: wings0
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: wings0