version: '3.8'

services:
  internal-reverse-proxy:
    image: traefik:v2.11
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - --api.insecure=true
      - --providers.docker.swarmMode=true
      - --providers.docker.network=local_proxy
      - --providers.docker.exposedByDefault=false
      - --entryPoints.web.address=:80
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - local_proxy
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role == manager"
      labels:
          - "shepherd.updates=true"

networks:
  local_proxy:
    external: true