version: '3.2'

services:
  agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: 
          - "node.platform.os == linux"
      labels:
        - "shepherd.updates=true"

  portainer:
    image: portainer/portainer-ce:latest
    command: 
      - -H tcp://tasks.agent:9001 
      - --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      # Comment out the below when deploying for the first time
      - local_proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"
      labels:
        - shepherd.updates=true
        - homepage.group=Eos Swarm Cluster
        - homepage.name=portainer
        - homepage.icon=portainer.png
        - homepage.href=https://192.168.6.7:9443
        - homepage.description=Docker management and deployment
        - homepage.widget.type=portainer
        - homepage.widget.target=_blank
        - homepage.widget.url=https://192.168.6.7:9443
        - homepage.widget.key=Insert here
        - homepage.widget.env=Eos-Swarm
        - traefik.enable=true
        - traefik.http.routers.portainer-rtr.entrypoints=websecure
        - traefik.http.routers.portainer-rtr.rule=Host(`portainer.local.sch-apps.com`)
        - traefik.http.routers.portainer-rtr.service=portainer-svc
        - traefik.http.services.portainer-svc.loadbalancer.server.port=9443

networks:
  agent_network:
    driver: overlay
    attachable: true
  # Comment out the below when deploying for the first time
  local_proxy:
    external: true

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/ceph/portainer_data"
      o: bind