#This file exists only as a template for the actual file. I didn't want to deal with this many Docker secrets.... So the actual file is just copied to Portainer.
# As such anything relating to a password is obviously getting ommitted....
version: '3.8'

services:
  panel:
    image: ccarney16/pterodactyl-panel:latest
    hostname: pterodactyl-panel
    networks:
      - proxy
    ports:
      - "8001:80"
    volumes:
      - "/mnt/ceph/ptero_data/panel:/data" #Appdata of Container
    environment:
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      APP_SERVICE_AUTHOR: "EMAIL"
      APP_URL: "https://SUB.DOMAIN.COM"
      APP_TIMEZONE: "America/New_York"       # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
      CACHE_DRIVER: "redis" #DON'T TOUCH
      SESSION_DRIVER: "redis" #DON'T TOUCH
      QUEUE_DRIVER: "redis" #DON'T TOUCH
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USER: "admin"
      REDIS_PASSWORD: REDIS-PASSWORD
      MAIL_FROM: "EMAIL"
      MAIL_DRIVER: "smtp"
      MAIL_HOST: "smtp.gmail.com"
      MAIL_PORT: "587"
      MAIL_USERNAME: "ACCOUNT-GMAIL"
      MAIL_PASSWORD: "APP_PASSWORD"
      MAIL_ENCRYPTION: “true”
      APP_DEBUG: “false”
      TRUSTED_PROXIES: "*"
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: "DATABASE-USER"
      DB_PASSWORD: DATABASE-PASSWORD
      DB_DATABASE: "DATABASE-USERNAME"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /mnt/ceph/ptero_data/redis:/root/redis
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - /mnt/ceph/ptero_data/madiadb:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  ptero_data:
    driver: local

networks:
  proxy:
    external: true