version: '3.8'

services:
  prowlarr:
    image: ghcr.io/hotio/prowlarr
    environment:
      - PUID=1000
      - PGID=999
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - '/mnt/ceph/prowlarr_data:/config'
    ports:
      - 9696:9696
    networks:
      - media
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == vpn"
      labels:
        - shepherd.updates=true
        - homepage.group=Media Acquisition
        - homepage.name=Prowlarr
        - homepage.icon=prowlarr.png
        - homepage.href=http://192.168.6.7:9696/
        - homepage.description=Subtitle Acquisition
        - homepage.widget.type=prowlarr
        - homepage.widget.url=http://192.168.6.7:9696
        - homepage.widget.key=3978745a0b7b4009bf63a40486a1615c

  bazarr:
    image: ghcr.io/hotio/bazarr
    environment:
      - PUID=1000
      - PGID=999
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - '/mnt/ceph/bazarr_data:/config'
      - '/mnt/samba/media:/media'
    ports:
      - 6767:6767
    networks:
      - media
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == vpn"
      labels:
        - shepherd.updates=true
        - homepage.group=Media Acquisition
        - homepage.name=Bazarr
        - homepage.icon=bazarr.png
        - homepage.href=http://192.168.6.7:6767/
        - homepage.description=Subtitle Acquisition
        - homepage.widget.type=bazarr
        - homepage.widget.url=http://192.168.6.7:6767
        - homepage.widget.key=845515585f029aa30d8ff949fff0182a

  sonarr:
    image: ghcr.io/hotio/sonarr
    environment:
      - PUID=1000
      - PGID=999
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - '/mnt/ceph/sonarr_data:/config'
      - '/mnt/samba/media:/media'
    ports:
      - 8989:8989
    networks:
      - media
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == vpn"
      labels:
        - shepherd.updates=true
        - homepage.group=Media Acquisition
        - homepage.name=Sonarr
        - homepage.icon=sonarr.png
        - homepage.href=http://192.168.6.7:8989/
        - homepage.description=Show Acquisition
        - homepage.widget.type=sonarr
        - homepage.widget.url=http://192.168.6.7:8989
        - homepage.widget.key=f979c4c17c0c48ccac97ad8f4fcdf36a

  radarr:
    image: ghcr.io/hotio/radarr
    environment:
      - PUID=1000
      - PGID=999
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - '/mnt/ceph/radarr_data:/config'
      - '/mnt/samba/media:/media'
    ports:
      - 7878:7878
    networks:
      - media
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == vpn"
      labels:
        - shepherd.updates=true
        - homepage.group=Media Acquisition
        - homepage.name=radarr
        - homepage.icon=radarr.png
        - homepage.href=http://192.168.6.7:7878/
        - homepage.description=Movie Acquisition
        - homepage.widget.type=radarr
        - homepage.widget.url=http://192.168.6.7:7878
        - homepage.widget.key=139cff2c5dc946b6ae4e9d9c74cc9408

volumes:
  prowlarr_data:
    driver: local
  bazarr_data:
    driver: local
  sonarr_data:
    driver: local
  radarr_data:
    driver: local

networks:
  media:
    name: media
    driver: overlay
    attachable: true
