version: '3.8'

services:
  prowlarr:
    image: ghcr.io/hotio/prowlarr
    environment:
      - PUID=1000
      - PGID=999
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - prowlarr_data:/config
    ports:
      - 9696:9696
    networks:
      - media
      - local_proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == vpn"
      labels:
        - traefik.enable=true
        - traefik.http.routers.prowlarr-rtr.entrypoints=web
        - traefik.http.routers.prowlarr-rtr.rule=Host(`prowlarr.local.sch-apps.com`)
        - traefik.http.routers.prowlarr-rtr.service=prowlarr-svc
        - traefik.http.services.prowlarr-svc.loadbalancer.server.port=9696
        - shepherd.updates=true
        - homepage.group=Media Acquisition
        - homepage.name=Prowlarr
        - homepage.icon=prowlarr.png
        - homepage.href=http://prowlarr.local.sch-apps.com
        - homepage.description=Indexer Management
        - docker-volume-backup.stop-during-backup=true

  bazarr:
    image: ghcr.io/hotio/bazarr
    environment:
      - PUID=1000
      - PGID=999
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - bazarr_data:/config
      - '/mnt/hdd_pool/media:/media'
    ports:
      - 6767:6767
    networks:
      - media
      - local_proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == vpn"
      labels:
        - traefik.enable=true
        - traefik.http.routers.bazarr-rtr.entrypoints=web
        - traefik.http.routers.bazarr-rtr.rule=Host(`bazarr.local.sch-apps.com`)
        - traefik.http.routers.bazarr-rtr.service=bazarr-svc
        - traefik.http.services.bazarr-svc.loadbalancer.server.port=6767
        - shepherd.updates=true
        - homepage.group=Media Acquisition
        - homepage.name=Bazarr
        - homepage.icon=bazarr.png
        - homepage.href=http://bazarr.local.sch-apps.com
        - homepage.description=Subtitle Acquisition
        - docker-volume-backup.stop-during-backup=true

  sonarr:
    image: ghcr.io/hotio/sonarr
    environment:
      - PUID=1000
      - PGID=999
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - sonarr_data:/config
      - '/mnt/hdd_pool/media:/media'
    ports:
      - 8989:8989
    networks:
      - media
      - local_proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == vpn"
      labels:
        - traefik.enable=true
        - traefik.http.routers.sonarr-rtr.entrypoints=web
        - traefik.http.routers.sonarr-rtr.rule=Host(`sonarr.local.sch-apps.com`)
        - traefik.http.routers.sonarr-rtr.service=sonarr-svc
        - traefik.http.services.sonarr-svc.loadbalancer.server.port=8989
        - shepherd.updates=true
        - homepage.group=Media Acquisition
        - homepage.name=Sonarr
        - homepage.icon=sonarr.png
        - homepage.href=http://sonarr.local.sch-apps.com
        - homepage.description=Show Acquisition
        - docker-volume-backup.stop-during-backup=true

  radarr:
    image: ghcr.io/hotio/radarr
    environment:
      - PUID=1000
      - PGID=999
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - radarr_data:/config
      - '/mnt/hdd_pool/media:/media'
    ports:
      - 7878:7878
    networks:
      - media
      - local_proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == vpn"
      labels:
        - traefik.enable=true
        - traefik.http.routers.radarr-rtr.entrypoints=web
        - traefik.http.routers.radarr-rtr.rule=Host(`radarr.local.sch-apps.com`)
        - traefik.http.routers.radarr-rtr.service=radarr-svc
        - traefik.http.services.radarr-svc.loadbalancer.server.port=7878
        - shepherd.updates=true
        - homepage.group=Media Acquisition
        - homepage.name=radarr
        - homepage.icon=radarr.png
        - homepage.href=http://radarr.local.sch-apps.com
        - homepage.description=Movie Acquisition
        - docker-volume-backup.stop-during-backup=true

  backup:
    image: offen/docker-volume-backup:v2
    environment:
      - BACKUP_FILENAME=acquisition-%Y-%m-%dT%H-%M-%S.tar.gz
      - BACKUP_CRON_EXPRESSION=20 7 * * * #Run at 7:20am UTC, 1:20AM CST
      - BACKUP_PRUNING_PREFIX=acquisition-
      - BACKUP_RETENTION_DAYS=7
      - GZIP_PARALLELISM=3
    volumes:
      - /dev/shm:/tmp
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/ceph/prowlarr_data:/backup/prowlarr:ro
      - /mnt/ceph/bazarr_data:/backup/bazarr:ro
      - /mnt/ceph/sonarr_data:/backup/sonarr:ro
      - /mnt/ceph/radarr_data:/backup/radarr:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/hdd_pool/cloud/B2/eos:/archive
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 2000M
      placement:
        constraints: 
          - "node.role == manager"
      labels:
        - shepherd.updates=true

volumes:
  prowlarr_data:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/ceph/prowlarr_data"
      o: bind
  bazarr_data:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/ceph/bazarr_data"
      o: bind
  sonarr_data:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/ceph/sonarr_data"
      o: bind
  radarr_data:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/ceph/radarr_data"
      o: bind

networks:
  local_proxy:
    external: true
  media:
    name: media
    driver: overlay
    attachable: true
