version: '3.8'

services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=999
      - UMASK=002
      - TZ=America/Chicago
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - '/mnt/ceph/qbittorrent_data:/config'
      - '/mnt/samba/media:/media'
    networks:
      - media
      - local_proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == vpn"
      labels:
        - traefik.enable=true
        - traefik.http.routers.qbittorrent-rtr.entrypoints=web
        - traefik.http.routers.qbittorrent-rtr.rule=Host(`qbittorrent.local.sch-apps.com`)
        - traefik.http.routers.qbittorrent-rtr.service=qbittorrent-svc
        - traefik.http.services.qbittorrent-svc.loadbalancer.server.port=8080
        - homepage.group=Media Acquisition
        - homepage.name=qBittorrent
        - homepage.icon=qbittorrent.png
        - homepage.href=http://qbittorrent.local.sch-apps.com
        - homepage.description=Content downloader
        - shepherd.updates=true

  jdownloader-2:
    image: jlesage/jdownloader-2
    ports:
      - "5800:5800"
    volumes:
      - '/mnt/ceph/jdownloader2_data:/config:rw'
      - '/mnt/samba/media:/media'
    networks:
      - local_proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - traefik.enable=true
        - traefik.http.routers.jdownloader-rtr.entrypoints=web
        - traefik.http.routers.jdownloader-rtr.rule=Host(`jdownloader.local.sch-apps.com`)
        - traefik.http.routers.jdownloader-rtr.service=jdownloader-svc
        - traefik.http.services.jdownloader-svc.loadbalancer.server.port=5800
        - homepage.group=Media Acquisition
        - homepage.name=JDownloader
        - homepage.icon=jdownloader.png
        - homepage.href=http://jdownloader.local.sch-apps.com
        - homepage.description=Web video downloader
        - shepherd.updates=true
  
volumes:
  qbittorrent_data:
    driver: local
  jdownloader2_data:
    driver: local

networks:
  local_proxy:
    external: true
  media:
    external: true