version: '3.8'

services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=999
      - UMASK=002
      - TZ=America/Chicago
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - '/mnt/ceph/qbittorrent_data:/config'
      - '/mnt/samba/media:/media'
    networks:
      - media
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == vpn"
      labels:
        - "shepherd.updates=true"

  jdownloader-2:
    image: jlesage/jdownloader-2
    ports:
      - "5800:5800"
    volumes:
      - '/mnt/ceph/jdownloader2_data:/config:rw'
      - '/mnt/samba/media:/media'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "shepherd.updates=true"
  
volumes:
  qbittorrent_data:
    driver: local
  jdownloader2_data:
    driver: local

networks:
  media:
    external: true