# To run:
# ansible-playbook playbooks/ansible_ssh.yaml -i inventories/eos.yaml --become-password-file=credentials/ansible_password.txt
---
- name: Set up ansible user ssh access
  hosts: vms
  remote_user: ansible
  vars_files:
    - /credentials/credentials.yaml

  tasks:
  - name: Set ansible ssh key
    ansible.posix.authorized_key:
      user: ansible
      state: present
      key: "{{ lookup('file', '../credentials/id_rsa.pub') }}"