# To run:
# ansible-playbook playbooks/dhcp_renew.yaml -i inventories/eos.yaml --become-password-file=credentials/ansible_password.txt
---
- name: Requests a DHCP renew on all assigned Ubuntu hosts
  hosts: pihole, docker
  remote_user: ansible
  become: true

  tasks:
    - name: DHCP Renew
      ansible.builtin.shell: |
        networkctl renew enp6s18