---
# To run:
# ansible-playbook playbooks/swarm/docker_data.yaml -i inventories/eos.yaml --become-password-file=credentials/ansible_eos_password.txt
- name: Set up Docker data folders
  hosts: sovereign-01
  remote_user: ansible
  become: true

  tasks:
    - name: Create docker volumes
      ansible.builtin.file:
        path: /mnt/ceph/{{ item }}
        state: directory
        owner: ansible
        group: docker
        mode: '0755'
      loop:
        - portainer_data
        - npm_data/npm
        - npm_data/npm-letsencrypt
        - influxdb_data
        - influxdb2_data
        - chronograf_data
        - loki_data
        - telegraf_data
        - telegraf_data/gpu
        - telegraf_data/standard
        - promtail_data
        - promtail_data/positions
        - folding_at_home/node1
        - folding_at_home/node2
        - folding_at_home/node3
        - jellyfin_data
        - overseerr_data
        - jellyseerr_data
        - prowlarr_data
        - bazarr_data
        - sonarr_data
        - radarr_data
        - qbittorrent_data
        - plex_data
        - homepage_data
        - tautulli_data
        - uptime-kuma_data
        - unpoller_data
        - prometheus_data
        - jellystat_data
        - jellystat_data/db
        - jellystat_data/jellystat
        - freshrss_data
        - jdownloader2_data
        - cephfs_media
        - cephfs_media/downloads
        - cephfs_media/downloads/incomplete
        - cephfs_media/downloads/completed
        - newarcadia_data
        - newarcadia_data/telegraf
        - krusader_data
        - filebrowser_data
        - ghost_data
        - ghost_data/ghost
        - ghost_data/db
        - kavita_data
        - mkvtoolnix_data
        - scratch_data
        - immich_data
        - immich_data/postgres
        - immich_data/model-cache
        - kometa_data
        - kometa_data/reports
        - varken_data
        - ytdl_data
        - ytdl_data/ytdl_material
        - ytdl_data/ytdl_db

    - name: Create docker volumes with insecure permissions
      ansible.builtin.file:
        path: /mnt/ceph/{{ item }}
        state: directory
        recurse: yes
        owner: ansible
        group: docker
        mode: '1777'
      loop:
        - grafana_data