# To run:
# ansible-playbook playbooks/swarm/file_shares_workers.yaml -i inventories/eos.yaml --become-password-file=credentials/ansible_eos_password.txt
---
- name: Install the cifs-utils and create file shares on the worker nodes
  hosts: defiant-03, voyager-01
  remote_user: ansible
  become: true

  tasks:
    - name: Install Samba
      ansible.builtin.apt:
        pkg:
          - cifs-utils

    - name: Create mount points for the media samba shares
      ansible.builtin.file:
        path: /mnt/samba/media/{{ item }}
        state: directory
        recurse: yes
        owner: ansible
        group: docker
        mode: '0755'
      loop:
        - media
        - downloads
        - disk-imports

    - name: Create mount points for the cloud storage samba shares
      ansible.builtin.file:
        path: /mnt/samba/cloud-storage/{{ item }}
        state: directory
        recurse: yes
        owner: ansible
        group: docker
        mode: '0755'
      loop:
        - dropbox
        - onedrive

    - name: Make the smb credentials directory and set the permissions
      ansible.builtin.file:
        path: /root/smbcredentials
        state: directory
        recurse: yes
        owner: root
        group: root
        mode: '0550'

    - name: Create the smb credentials file, will be edited manually
      ansible.builtin.file:
        path: /root/smbcredentials/eos
        state: touch

    - name: Create fstab entries, will be verified manually and then mounted
      ansible.builtin.shell: |
        echo '//192.168.100.192/Media /mnt/samba/media/media cifs credentials=/root/smbcredentials/eos,uid=1000,gid=1000 0 0' >> /etc/fstab
        echo '//192.168.100.42/Disk-Imports /mnt/samba/media/disk-imports cifs credentials=/root/smbcredentials/eos,uid=1000,gid=1000 0 0' >> /etc/fstab
        echo '//192.168.100.42/Downloads /mnt/samba/media/downloads cifs credentials=/root/smbcredentials/eos,uid=1000,gid=1000 0 0' >> /etc/fstab
        echo '//192.168.100.42/Dropbox /mnt/samba/cloud-storage/dropbox cifs credentials=/root/smbcredentials/eos,uid=1000,gid=1000 0 0' >> /etc/fstab
        echo '//192.168.100.42/OneDrive /mnt/samba/cloud-storage/onedrive cifs credentials=/root/smbcredentials/eos,uid=1000,gid=1000 0 0' >> /etc/fstab