# To run:
# ansible-playbook playbooks/swarm/media_cephfs.yaml -i inventories/eos.yaml --become-password-file=credentials/ansible_eos_password.txt
- name: Set up Symbolic links between the Ceph fs mount and the media mount
  hosts: defiant-03, voyager-01
  remote_user: ansible
  become: true

  tasks:
    - name: Create mount points for the media samba shares
      ansible.builtin.file:
        path: /mnt/samba/media/cephfs_media
        state: directory
        recurse: yes
        owner: ansible
        group: docker
        mode: '0755'

    - name: Create fstab entry, will be verified manually and then mounted
      ansible.builtin.shell: |
        echo '10.1.100.30,10.1.100.31,10.1.100.32:/swarm_prod/cephfs_media     /mnt/samba/media/cephfs_media    ceph    name=dockerswarm,secret=AQDSvgBmT1iaFhAAMj76ud9oV1sw642LhoeZEg==,rw,noatime,_netdev    0       2' >> /etc/fstab