# To run:
# ansible-playbook playbooks/swarm/remount_all.yaml -i inventories/eos.yaml --become-password-file=credentials/ansible_eos_password.txt
---
- name: Remount all mount points
  hosts: swarm
  remote_user: ansible
  become: true

  tasks:
    - name: Mount all mount points in fstab
      ansible.builtin.shell: |
        mount -a