version: '3.8'

services:
  loki:
    image: grafana/loki:2.7.5
    ports:
      - '3100:3100'
    environment:
      - TZ=America/Chicago
    volumes:
      - '/mnt/ceph/loki_data:/etc/loki'
    command: -config.file=/etc/loki/local-config.yaml
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "shepherd.updates=true"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - '/mnt/ceph/prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "shepherd.updates=true"
    networks:
      - monitoring

  influxdb:
    image: influxdb:1.8.10
    environment:
      - TZ=America/Chicago
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=$INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD=$INFLUXDB_ADMIN_PASSWORD
    ports:
      - '8086:8086'
    volumes:
      - '/mnt/ceph/influxdb_data:/var/lib/influxdb'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "shepherd.updates=true"
    networks:
      - monitoring

  influxdb2:
    image: influxdb:2
    environment:
      - TZ=America/Chicago
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=$INFLUXDB2_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD=$INFLUXDB2_ADMIN_PASSWORD
    ports:
      - '8087:8086'
    volumes:
      - '/mnt/ceph/influxdb2_data:/var/lib/influxdb'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "shepherd.updates=true"
    networks:
      - monitoring

volumes:
  influxdb_data:
    driver: local
  influxdb2_data:
    driver: local
  loki_data:
    driver: local
  prometheus_data:
    driver: local

networks:
  monitoring:
    external: true
  local_proxy:
    external: true