version: "3.8"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_ENDPOINT_IP=$ENDPOINT_IP
      - WIREGUARD_ENDPOINT_PORT=$ENDPOINT_PORT
      - WIREGUARD_PUBLIC_KEY=$PUBLIC_KEY
      - WIREGUARD_PRIVATE_KEY=$PRIVATE_KEY
      - WIREGUARD_ADDRESSES=$IP_ADDRESS
      - HTTPPROXY=on
      - DNS_ADDRESS=192.168.8.1
    networks:
      - gluetun

networks:
  gluetun:
    name: gluetun