version: '3.8'

services:
  server:
    image: ghcr.io/immich-app/immich-server:$IMMICH_VERSION:-release
    volumes:
      - $UPLOAD_LOCATION:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE_NAME=$DB_DATABASE_NAME
      - DB_DATA_LOCATION=$DB_DATA_LOCATION
      - TZ=$TZ
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    healthcheck:
      disable: false
    networks:
      - local_proxy
      - immich
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.nvidia == true"
      labels:
        - traefik.enable=true
        - traefik.http.routers.immich-rtr.entrypoints=web
        - traefik.http.routers.immich-rtr.rule=Host(`immich.local.sch-apps.com`)
        - traefik.http.routers.immich-rtr.service=immich-svc
        - traefik.http.services.immich-svc.loadbalancer.server.port=3001
        - homepage.group=Media Front End
        - homepage.name=immich
        - homepage.icon=immich.png
        - homepage.href=http://immich.local.sch-apps.com
        - homepage.description=The photo and video repository

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:main-cuda
    volumes:
      - /mnt/ceph/immich_data/model-cache:/cache
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    healthcheck:
      disable: false
    networks:
      - local_proxy
    deploy:
      mode: global
      placement:
        constraints: 
          - "node.labels.nvidia == true"
      labels:
        - shepherd.updates=true
        - traefik.enable=true
        - traefik.http.routers.immich-rtr.entrypoints=web
        - traefik.http.routers.immich-rtr.rule=Host(`immich-ml.local.sch-apps.com`)
        - traefik.http.routers.immich-rtr.service=immich-svc
        - traefik.http.services.immich-svc.loadbalancer.server.port=3003

  redis:
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - immich
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - "shepherd.updates=true"

  database:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_DB: $DB_DATABASE_NAME
      POSTGRES_INITDB_ARGS: '--data-checksums'
      TZ: $TZ
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='$DB_DATABASE_NAME' --username='$DB_USERNAME' || exit 1; Chksum="$$(psql --dbname='$DB_DATABASE_NAME' --username='$DB_USERNAME' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    networks:
      - immich
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - shepherd.updates=true

volumes:
  immich_data:
    driver: local

networks:
  immich:
    name: immich
    driver: overlay
  local_proxy:
    external: true
  