version: '3.8'

services:
  mkvtoolnix:
    image: jlesage/mkvtoolnix
    ports:
      - "5801:5800"
    volumes:
      - '/mnt/ceph/mkvtoolnix_data:/config:rw'
      - '/mnt/samba/media:/media:rw'
    networks:
      - local_proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.host_type == proxmox"
          - "node.labels.connection == standard"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mkvtoolnix-rtr.entrypoints=web"
        - "traefik.http.routers.mkvtoolnix-rtr.rule=Host(`mkvtoolnix.local.sch-apps.com`)"
        - "traefik.http.routers.mkvtoolnix-rtr.service=mkvtoolnix-svc"
        - "traefik.http.services.mkvtoolnix-svc.loadbalancer.server.port=5800"
        - "shepherd.updates=true"

  kometa:
    image: kometateam/kometa
    environment:
      - TZ=America/Chicago
      - KOMETA_RUN=true
      - KOMETA_CONFIG=/db_configs/config.yml
    volumes:
      - '/mnt/samba/cloud-storage/dropbox/VS Studio Code/homelab/EOS-Cluster/Docker-Swarm/Media/Management/kometa_configs:/db_configs'
      - /mnt/ceph/kometa_data:/config
    deploy:
      mode: replicated
      replicas: 0
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - shepherd.updates=true

volumes:
  mkvtoolnix_data:
    driver: local
  kometa_data:
    driver: local

networks:
  local_proxy:
    external: true