version: '3.9'

services:

  kavita:
    image: ghcr.io/kareadita/kavita:latest
    environment:
      - TZ=America/Chicago
    volumes:
      - '/mnt/samba/cloud-storage/dropbox/Kavita-Content:/content'
      - /mnt/ceph/kavita_data:/kavita/config
    ports:
      - "5000:5000"
    networks:
      - cftunnel
      - local_proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == worker"
          - "node.labels.connection == standard"
      labels:
        - traefik.enable=true
        - traefik.http.routers.kavita-rtr.entrypoints=web
        - traefik.http.routers.kavita-rtr.rule=Host(`kavita.local.sch-apps.com`)
        - traefik.http.routers.kavita-rtr.service=kavita-svc
        - traefik.http.services.kavita-svc.loadbalancer.server.port=5000
        - shepherd.updates=true
        - homepage.group=Media Front End
        - homepage.name=kavita
        - homepage.icon=kavita.png
        - homepage.href=http://kavita.local.sch-apps.com
        - homepage.description=Books, Comics, and Graphic Novels
        - homepage.widget.type=kavita
        - homepage.widget.target=_blank
        - homepage.widget.url=http://kavita.local.sch-apps.com
        - homepage.widget.username=/run/secrets/kavita_username
        - homepage.widget.password=/run/secrets/kavita_password

volumes:
  kavita_data:
    driver: local

networks:
  cftunnel:
    external: true
  local_proxy:
    external: true

secrets:
  kavita_username:
    external: true
  kavita_password:
    external: true
