version: "3.8"

services:
  sovereign-01:
    image: lscr.io/linuxserver/foldingathome:latest
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Chicago
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - 'folding_at_home/node1:/config'
    ports:
      - 7396:7396
      - 36330:36330 #optional
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: "no"
      placement:
        constraints: 
          - "node.hostname == sovereign-01"

  sovereign-02:
    image: lscr.io/linuxserver/foldingathome:latest
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Chicago
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - 'folding_at_home/node2:/config'
    ports:
      - 7397:7396
      - 36331:36330 #optional
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: "no"
      placement:
        constraints: 
          - "node.hostname == sovereign-02"

  sovereign-03:
    image: lscr.io/linuxserver/foldingathome:latest
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Chicago
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - 'folding_at_home/node3:/config'
    ports:
      - 7398:7396
      - 36332:36330 #optional
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: "no"
      placement:
        constraints: 
          - "node.hostname == sovereign-03"

volumes:
  folding_at_home:
    driver: local